version: "3"

services:
  dashboard-application:
    build: ./dashboard
    command: python /home/dashboard/index.py
    environment:
      - PYTHONPATH=/home
    volumes:
      - ./dashboard:/home/dashboard
    ports:
      - "80:8000"
